### PR TITLE
Add the introduction video to the readme and site index.

### PR DESCRIPTION
**Pull request by bayleedev**
ping @tinytacoteam/zazu-core 

@amjith and I made an introduction video for zazu. This pr provides a link from the readme and the website.

### CODE REVIEW

**Comment by amjith** [comment]
@blainesch Can you change the png file to a shot that actually shows zazu in the screen?

**Comment by bayleedev** [comment]
@amjith I updated the png here and the thumbnail on vimeo.

**Comment by amjith** [comment]
Awesome! Looks good. 👍

**Comment by afaur** [comment]
👍 Great job

**Pull request merged**
