### PR TITLE
Correct configuration.md

### PR DESCRIPTION
**Pull request by junebash**
'Command+space' doesn't work in config file; 'cmd+space' does.

### CODE REVIEW

**Comment by bayleedev** [comment]
Thank you!

**Comment by bayleedev** [comment]
Oh, snap you made this to the wrong branch. I'll try and cherry pick your code to master so it doesn't get overwritten.

**Comment by bayleedev** [comment]
The git-foo is strong with this one:
https://github.com/tinytacoteam/zazu/commits/master

**Comment by junebash** [comment]
D'oh, sorry, I'm a github n00b. >_<

**Pull request merged**
