### PR TITLE
Fix references to old naming convention. [skip ci]

### PR DESCRIPTION
**Pull request by bayleedev**
Reviewer @eldinoyev Thanks!

### CODE REVIEW

**Review by eldinoyev — APPROVED** [review]
👍

**Comment by bayleedev** [comment]
@eldinoyev if you approve changes, you can merge the pr! [:

I wrote up the workflow for core devs over [here](https://github.com/tinytacoteam/zazu/blob/master/.github/CONTRIBUTING.md#core-team-guidelines) :D

**Comment by eldinoyev** [comment]
@blainesch Oh nice! Thank you for the heads up.

**Comment by bayleedev** [comment]
Don't forget to delete the branch too [:

**Comment by eldinoyev** [comment]
Ahh that too, looks like you took care of it.

**Pull request merged**
