### PR TITLE
Add zazu-battery to the plugin page

### PR DESCRIPTION
**Pull request by danielbayerlein**
[zazu-battery](https://github.com/danielbayerlein/zazu-battery) shows information about your battery.

### CODE REVIEW

**Comment by bayleedev** [comment]
@danielbayerlein since this is mac-specific would a better name be `zazu-mac-battery` ? Similar to [`zazu-mac-vpn`](https://github.com/amjith/zazu-mac-vpn) plugin.

**Comment by danielbayerlein** [comment]
@blainesch At the moment only macOS is implemented. You can easily integrate other operating systems, see https://github.com/danielbayerlein/zazu-battery/blob/master/src/index.js#L6. I hope someone adds support for Linux and Windows. 😉

**Comment by bayleedev** [comment]
Fair enough!

**Comment by danielbayerlein** [comment]
@blainesch Thank you 😉

**Pull request merged**
