### PR TITLE
Update to reflect Cask status

### PR DESCRIPTION
**Pull request by rouzbeh84**
Couldn't find via brew/Cask so thought I'd update this for you real quick :). Great work and keep it up!

### CODE REVIEW

**Comment by bayleedev** [comment]
@rouzbeh84 I just updated the instructions to include `brew update`, since it's a new cask you'll likely need to pull in the latest changes. If you still can't find it, reopen this issue please. I hope this helps! [:

**Comment by rouzbeh84** [comment]
Ah thanks @blainesch! I had just freshly tapped cask and updated but got the following message but I must have done something wrong locally. my mistake!

**Comment by bayleedev** [comment]
What does `brew doctor` say?

Here is the cask for reference:
https://github.com/caskroom/homebrew-cask/pull/28546

**Comment by rouzbeh84** [comment]
Oh no, sorry, i should have mentioned I got it working. I think it was a local hiccup on the update. Thanks!

**Comment by bayleedev** [comment]
Oh great!

**Pull request closed without merging**
