### PR TITLE
Add VPN package.

### PR DESCRIPTION
**Pull request by amjith**
@blainesch

### CODE REVIEW

**Comment by bayleedev** [comment]
1___usr_local_bin_tmux__tmux_

The command doesn't appear to work on sierra, unless I'm doing something wrong.

network

**Comment by amjith** [comment]
So `scutil --nc list` wasn't listing any connections? 

Can you try `scutil --nc start "NR PDX VPN"` to see if the VPN connects?

**Comment by bayleedev** [comment]
```
▶ scutil --nc start "NR PDX VPN"
No service
```

I verified the name was correct.

**Comment by amjith** [comment]
Searching for problems with scutil in Sierra doesn't yield any results. I don't have a Sierra build to test this. But I wonder if this is a symptom of a more systemic problem such as you didn't agree to the terms and conditions for XCode after the install or something equally silly.

**Comment by bayleedev** [comment]
I reinstalled from scratch (not an update) and it is working now. Thanks!

**Comment by amjith** [comment]
When will it show up on zazu website? :smile:

**Comment by bayleedev** [comment]
Oh yeah, I have to deploy xD

http://zazuapp.org/packages/

**Pull request merged**
