### PR TITLE
Add zazu-github to the plugin page

### PR DESCRIPTION
**Pull request by danielbayerlein**
[zazu-github](https://github.com/danielbayerlein/zazu-github) is a search for GitHub repositories with [github.com](https://github.com).

### CODE REVIEW

**Comment by bayleedev** [comment]
What's the biggest difference between this and the [github repos](https://github.com/gabrielpoca/zazu-github-repos) plugin? Just by checking it looks like this plugin doesn't require an api key, right?

**Comment by danielbayerlein** [comment]
@blainesch Right, this plugin does not require an authentication.

Note:
> For unauthenticated requests, the rate limit allows you to make up to 10 requests per minute.

**Comment by bayleedev** [comment]
Thank you for the contribution

**Comment by danielbayerlein** [comment]
@blainesch You are welcome!

**Pull request merged**
