### PR TITLE
Fix border and shadow

### PR DESCRIPTION
**Pull request by afaur**
Fixes https://github.com/tinytacoteam/zazu/issues/162

This adds radius and drop shadow in the markdown.  Since the radius is the same on mac osx it looks no different.  I am unsure if the drop shadow is actually working or not.

@amjith, or @blainesch please take a look.
Could someone running linux mint or ubuntu also take a look?

### CODE REVIEW

**Comment by bayleedev** [comment]
This should be tested with a few variations.. I think transparency is disabled on windows, and also we should try with a linux that has 3D rendering turned on.

**Comment by filipelinhares** [comment]
Hey guys!

Applying those changes in Ubuntu, I get a white background in the corners:
image

When debugging I found this weird behavior. The background is blinking with the cursor.
ezgif com-crop

Do you have any ideia why it's happening?

**Comment by afaur** [comment]
Might be because of this:

"On Linux users have to put --enable-transparent-visuals --disable-gpu in the command line to disable GPU and allow ARGB to make transparent window, this is caused by an upstream bug that alpha channel doesn’t work on some NVidia drivers on Linux."

Sources:
https://discuss.atom.io/t/how-to-get-a-frameless-window-with-border-radius/23591/3
http://electron.atom.io/docs/api/frameless-window/

Not exactly sure how we add those options @blainesch do you have any ideas here?

I guess on linux zazu would make sure that your shortcut or startup script has those flags passed in when running zazu at startup?

**Comment by afaur** [comment]
I am really curious about the cursor blinking as well.  Maybe I missed something in my code changes for that part.  I really appreciate you trying this out @filipelinhares

**Comment by bayleedev** [comment]
This won't work cross platform.

**Pull request closed without merging**
