### PR TITLE
Traverse History

### PR DESCRIPTION
**Pull request by afaur**
`ctrl+,` and `ctrl+.` will move backward and forward through history.  Attempted to use `ctrl+h` and `ctrl+l` however `ctrl+h` deletes input to the left of the cursor.

### CODE REVIEW

**Comment by amjith** [comment]
I might prefer `alt+p` and `alt+n` instead of `Ctrl+,` and `Ctrl+.`

**Comment by afaur** [comment]
@amjith Can you test and see if that shortcut will work correctly?  I don't see a problem with that if it works.

**Comment by amjith** [comment]
I just had a conversation with @blainesch. I'd like to make an argument for going back to up/down arrow. Here's why:

People are used to the up/down key. Using alt-p/alt-n is a weird key combo that no one will use. Zazu ships with the fallback search so there is always a result. So the case where the up/down arrow breaks is an extremely rare case that doesn't warrant a change in the key combo.

**Comment by afaur** [comment]
@amjith I think the problem with the `up/down` `arrow` would be that `down` will take you to the first result if you have one.  

Since you said 'go back' maybe you are suggesting that the user select the query before pressing the `up/down`?  If that is the case would that really be more intuitive?  Seems like it would still merit some documentation exploring and a `ctrl+a` to select the text in the input.

**Comment by amjith** [comment]
There I fixed it for you. #262 

😝

**Pull request closed without merging**
