### PR TITLE
Reset screens if current screen does not exist.

### PR DESCRIPTION
**Pull request by bayleedev**
Possible fix for #246

### CODE REVIEW

**Comment by bayleedev** [comment]
@eldinoyev can you take a look at this?

**Comment by eldinoyev** [comment]
After several attempts between screens and trying what you said @RonCrocker did to produce this error, I wasn't able to reproduce the issue.
However, the update to Screens looks great and works perfectly for me on El Capitan!

**Review by eldinoyev — APPROVED** [review]

**Comment by eldinoyev** [comment]
@blainesch Not sure if you'll want me to merge this one considering I couldn't reproduce the problem :/

**Comment by bayleedev** [comment]
Thanks for taking a look @eldinoyev !!

**Pull request merged**
