### PR TITLE
Create zazu-solarized

### PR DESCRIPTION
**Pull request by marcpaul**
All pull requests should go to `master`, even the documentation is in `master`
under `./docs/`.

### CODE REVIEW

**Comment by bayleedev** [comment]
It's on master here

https://github.com/tinytacoteam/zazu/commit/b63b22720c18903b6b414d58f36ef805009a0c92

**Comment by marcpaul** [comment]
i should have named it dark so i can make a light one too...
should i rename my github project and make another pull request?

**Comment by bayleedev** [comment]
I'm happy to help with those changes if you do.

**Comment by marcpaul** [comment]
hey!

i have renamed the repo to
marcpaul/zazu-solarized-dark-theme

what should i do next?
or can you simply change the link?

thanks for your help

marc

**Comment by bayleedev** [comment]
@marcelocg I've updated the docs.

http://zazuapp.org/themes/

**Comment by marcpaul** [comment]
kool thanks

**Pull request closed without merging**
