### PR TITLE
Change "Mac OS X" to "macOS"

### PR DESCRIPTION
**Pull request by 2shortplanks**

### CODE REVIEW

**Comment by bayleedev** [comment]
Thank you!

**Comment by bayleedev** [comment]
whoops you made the pr to `gh-pages` not master. I keep merging these >.<

I'll cherry-pick it into master [:

**Comment by bayleedev** [comment]
Done.

**Comment by 2shortplanks** [comment]
Shouldn't this have been merged into gh-pages? It's a patch to the website,
not the app...

**Comment by bayleedev** [comment]
Nope `gh-pages` is auto-generated from `master` in the `docs` folder. This allows a single pull request to introduce a feature, update the changelog and update the docs without coordination.

**Pull request merged**
